[package]
name = "treasury"
type = "contract"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-devnet.2-patch.1", directory = "noir-projects/aztec-nr/aztec" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-devnet.2-patch.1", directory = "noir-projects/aztec-nr/compressed-string" }
address_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-devnet.2-patch.1", directory = "noir-projects/aztec-nr/address-note" }
token = { git = "https://github.com/defi-wonderland/aztec-standards/", tag = "v4.0.0-devnet.2-patch.1", directory = "src/token_contract"}
nft = { git = "https://github.com/defi-wonderland/aztec-standards/", tag = "v4.0.0-devnet.2-patch.1", directory = "src/nft_contract"}


