[package]
name = "members"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-nightly.20260204", directory = "noir-projects/aztec-nr/aztec" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-nightly.20260204", directory = "noir-projects/aztec-nr/compressed-string" }
address_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-nightly.20260204", directory = "noir-projects/aztec-nr/address-note" }
contract_instance_registry = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-nightly.20260204", directory = "noir-projects/noir-contracts/contracts/protocol_interface/contract_instance_registry_interface" }
bignum = { tag = "v0.9.0", git = "https://github.com/noir-lang/noir-bignum" }
