[package]
name = "nft_contract"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-nightly.20260204", directory = "noir-projects/aztec-nr/aztec" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-nightly.20260204", directory = "noir-projects/aztec-nr/compressed-string" }
contract_instance_registry = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-nightly.20260204", directory = "noir-projects/noir-contracts/contracts/protocol_interface/contract_instance_registry_interface" }
